color0 #131316
color1 #ffb4ab
color2 #c1c1ff
color3 #c6c4dd
color4 #e9b9d3
color5 #c1c1ff
color6 #c6c4dd
color7 #e5e1e6
color8 #918f9a
color9 #ffb4ab
color10 #c1c1ff
color11 #c6c4dd
color12 #e9b9d3
color13 #c1c1ff
color14 #c6c4dd
color15 #e5e1e6

cursor                #e5e1e6
cursor_text_color     #131316
background            #131316
foreground            #e5e1e6
selection_foreground  #c8c5d0
selection_background  #47464f
active_border_color   #c1c1ff
inactive_border_color #47464f
url_color             #c1c1ff

active_tab_foreground   #242478
active_tab_background   #c1c1ff
inactive_tab_foreground #c8c5d0
inactive_tab_background #47464f
cursor_trail_color      #c8c5d0
